local function deprecated_alias(funcname)
	return function(...)
		Debug.PrintStacktrace()
		Debug.Message("deprecated, use " .. funcname .. " instead")
		return load('return ' .. funcname .. '(...)')(...)
	end
end

--Functions deprecated since version 40.0:
Auxiliary.AskAny                        = deprecated_alias("Duel.AskAny")
Auxiliary.AskEveryone                   = deprecated_alias("Duel.AskEveryone")
Auxiliary.AnnounceAnotherAttribute      = deprecated_alias("Duel.AnnounceAnotherAttribute")
Auxiliary.AnnounceAnotherRace           = deprecated_alias("Duel.AnnounceAnotherRace")
Auxiliary.SelectEffect                  = deprecated_alias("Duel.SelectEffect")
Auxiliary.PlayFieldActional                = deprecated_alias("Duel.ActivateFieldActional")
Auxiliary.CheckPendulumZones            = deprecated_alias("Duel.CheckPendulumZones")
Auxiliary.nzatk                         = deprecated_alias("Card.HasNonZeroAttack")
Auxiliary.nzdef                         = deprecated_alias("Card.HasNonZeroDefense")
Auxiliary.disfilter1                    = deprecated_alias("Card.IsNegatableMonster")
Auxiliary.disfilter2                    = deprecated_alias("Card.IsNegatableActionalTrap")
Auxiliary.disfilter3                    = deprecated_alias("Card.IsNegatable")
Auxiliary.HasCounterListed              = deprecated_alias("Card.ListsCounter")
Auxiliary.CanPlaceCounter               = deprecated_alias("Card.PlacesCounter")
Auxiliary.EquipByEffectLimit            = deprecated_alias("Card.EquipByEffectLimit")
Auxiliary.EquipByEffectAndLimitRegister = deprecated_alias("Card.EquipByEffectAndLimitRegister")
Auxiliary.IsMaterialListCode            = deprecated_alias("Card.ListsCodeAsMaterial")
Auxiliary.IsMaterialListSetCard         = deprecated_alias("Card.ListsArchetypeAsMaterial")
Auxiliary.IsArchetypeCodeListed         = deprecated_alias("Card.ListsCodeWithArchetype")
Auxiliary.IsCodeListed                  = deprecated_alias("Card.ListsCode")
Auxiliary.IsCardTypeListed              = deprecated_alias("Card.ListsCardType")
Auxiliary.HasListedSetCode              = deprecated_alias("Card.ListsArchetype")
Auxiliary.IsGuardianState                 = deprecated_alias("Guardian.EffectStatusCondition")
Auxiliary.IsNotGuardianState              = deprecated_alias("Auxiliary.NOT(Guardian.EffectStatusCondition)")
Auxiliary.GuardianNormalCondition         = deprecated_alias("Guardian.NormalStatusCondition")
Auxiliary.EnableGuardianAttribute         = deprecated_alias("Guardian.AddProcedure")
Auxiliary.EnableGuardianReturn            = deprecated_alias("Guardian.AddProcedure")
Auxiliary.GuardianReturnReg               = deprecated_alias("Guardian.SummonRegister")
Auxiliary.GuardianReturnOperation         = deprecated_alias("Guardian.ReturnOperation")
Auxiliary.FilterFaceupFunction          = deprecated_alias("Auxiliary.FilterFaceup")

local function deleted_function(message)
	return function() error("This function is deleted. " .. message,2) end
end
--Deleted functions
Auxiliary.CallToken             = deleted_function("Use Duel.LoadCardScript or Duel.LoadScript instead.")
Auxiliary.GuardianReturnCondition = deleted_function("Check Guardian.MandatoryReturnCondition and Guardian.OptionalReturnCondition for more details.")
Auxiliary.GuardianReturnTarget    = deleted_function("Check Guardian.MandatoryReturnTarget and Guardian.OptionalReturnTarget for more details.")
